import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  HelpCircle,
  Image,
  Info,
  Laptop,
  Loader2,
  Map,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pizza,
  Plus,
  RefreshCw,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  MapPin,
  AlertCircle,
  Bell,
  Camera,
  Shield,
  ShieldAlert,
  Siren,
} from "lucide-react"

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: Pizza,
  ellipsis: MoreVertical,
  more: MoreHorizontal,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  map: Map,
  mapPin: MapPin,
  alert: AlertCircle,
  notification: Bell,
  camera: Camera,
  shield: Shield,
  shieldAlert: ShieldAlert,
  siren: Siren,
  info: Info,
  refresh: RefreshCw,
  check: Check,
  twitter: Twitter,
}

